### ISSUE TITLE
Autohotkey script for opening Files with Win+E displays wrong

### ISSUE THREAD

**Issue by gave92** [files-community/Website#22] opened 2021-10-07 23:55 UTC
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

![image](https://user-images.githubusercontent.com/9673091/136477298-524c568a-027e-484f-a00c-51689898c421.png)

### Steps To Reproduce

1. Go to "https://files.community/docs/configuring/configure-win-e"

### Expected behavior

See the correct script with slashes as;
`FilesLocation := USERPROFILE . "\AppData\Local\Microsoft\WindowsApps\Files.exe"`

**Comment by TheOnlyTails** [comment] 2021-10-08 05:12
Duplicate of #23

**Closed by TheOnlyTails** 2021-10-08 05:12 UTC
Labels: bug
