### ISSUE TITLE
Use more reliable element like `InfoBar`

### ISSUE THREAD

**Issue by Lamparter** [files-community/Website#435] opened 2023-05-30 10:24 UTC
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge Beta/Dev/Canary

### Description

The donation section on the download page is broken and destroys the look of the page. `InfoBar` would be more appropriate.

### Steps To Reproduce

1. Go to https://files.community/download
2. See the error

### Expected behavior

The donation element should not destroy the looks of the website. Instead, use a more reliable pre-built element like `fluent-svelte`'s `<InfoBar />`

### Relevant Assets

![image](https://github.com/files-community/Website/assets/71598437/86906d5b-55cd-46c9-af16-8de89893b1ce)

**Comment by TheOnlyTails** [comment] 2023-05-30 11:21
We do use an `<InfoBar>`: https://github.com/files-community/Website/blob/main/src/routes/download/+page.svelte#L46-L63

**Comment by TheOnlyTails** [comment] 2023-05-30 20:06
I'm gonna be very busy in the next few days (i have my comp sci finals!), so you should go right ahead

**Comment by chingucoding** [comment] 2023-06-01 19:02
Exactly which browser are you using to reproduce this issue? I just tried in Edge Dev and the downloads page looks fine to me.

**Comment by chingucoding** [comment] 2023-06-01 19:45
If you don't mind I would close this since this sounds more like an error in the browser than our code.

**Closed** 2023-06-01 19:45 UTC
Labels: bug
